INSERT INTO USER (USER_ID, USER_NAME, PASSWORD, USE_STATE) VALUES ('superuser', 'super~', '1234!@#$', 'USE');

INSERT INTO USER_AUTHORITY (USER_ID, AUTHORITY_ID) VALUES ('superuser', 'ROLE_SUPER');

INSERT INTO AUTHORITY (AUTHORITY_ID, AUTHORITY_NAME, DESCRIPTION, USE_STATE) VALUES ('ROLE_SUPER', '슈퍼권한', '슈퍼권한입니다.', 'USE');

INSERT INTO AUTHORITY_ACCESS (AUTHORITY_ID, ACCESS_MODE) VALUES ('ROLE_SUPER', 'READ');
INSERT INTO AUTHORITY_ACCESS (AUTHORITY_ID, ACCESS_MODE) VALUES ('ROLE_SUPER', 'WRITE');

INSERT INTO AUTHORITY_MENU (AUTHORITY_ID, MENU_ID) VALUES ('ROLE_SUPER', 1);
INSERT INTO AUTHORITY_MENU (AUTHORITY_ID, MENU_ID) VALUES ('ROLE_SUPER', 2);
INSERT INTO AUTHORITY_MENU (AUTHORITY_ID, MENU_ID) VALUES ('ROLE_SUPER', 3);
INSERT INTO AUTHORITY_MENU (AUTHORITY_ID, MENU_ID) VALUES ('ROLE_SUPER', 4);
INSERT INTO AUTHORITY_MENU (AUTHORITY_ID, MENU_ID) VALUES ('ROLE_SUPER', 5);

INSERT INTO MENU (MENU_ID, PARENT_MENU_ID, MENU_NAME, URI, DESCRIPTION, DISPLAY_ORDER, USE_STATE) VALUES (1, NULL, 'SYSTEM', NULL, NULL, NULL, 'USE');
INSERT INTO MENU (MENU_ID, PARENT_MENU_ID, MENU_NAME, URI, DESCRIPTION, DISPLAY_ORDER, USE_STATE) VALUES (2, 1, 'USER MANAGE', '/user/listview.do', NULL, NULL, 'USE');
INSERT INTO MENU (MENU_ID, PARENT_MENU_ID, MENU_NAME, URI, DESCRIPTION, DISPLAY_ORDER, USE_STATE) VALUES (3, 1, 'AUTHORITY MANAGE', '/authority/view.do', NULL, NULL, 'USE');
INSERT INTO MENU (MENU_ID, PARENT_MENU_ID, MENU_NAME, URI, DESCRIPTION, DISPLAY_ORDER, USE_STATE) VALUES (4, 1, 'MENU MANAGE', '/menu/view.do', NULL, NULL, 'USE');
INSERT INTO MENU (MENU_ID, PARENT_MENU_ID, MENU_NAME, URI, DESCRIPTION, DISPLAY_ORDER, USE_STATE) VALUES (5, 1, 'CODE MANAGE', '/code/view.do', NULL, NULL, 'USE');

INSERT INTO MENU_DEPENDENCE (SEQUENCE, MENU_ID, DEPENDENCE_URI) VALUES (1, 3, '/authority/access/list.do');
